language: nodejs
sudo: required
services:
  - docker

before_install:
  - docker build -t snmmaurya/frontend -f Dockerfile.dev .

script:
  - docker run snmmaurya/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "services"
  env: "snm-test-stage"
  bucket_name: "elasticbeanstalk-ap-south-1-106328716869"
  bucket_path: "services"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"